Repository patternfly/patternfly, pull requests merged in 2018-08, with the labels that each got.

#488 Improves page layout
  package-lock.json
  src/patternfly/components/Backdrop/styles.scss
  src/patternfly/components/BackgroundImage/styles.scss
  src/patternfly/components/Card/styles.scss
  src/patternfly/demos/PageTest/docs/code.md
  src/patternfly/demos/PageTest/docs/design.md
  src/patternfly/demos/PageTest/examples/index.js
  src/patternfly/demos/PageTest/examples/page-test-example1.hbs
  src/patternfly/demos/PageTest/examples/page-test-example2.hbs
  src/patternfly/demos/PageTest/page-test.hbs
  src/patternfly/demos/PageTest/styles.scss
  src/patternfly/layouts/Page/docs/code.md
  src/patternfly/layouts/Page/examples/page-layout-example.hbs
  src/patternfly/layouts/Page/page-section.hbs
  src/patternfly/layouts/Page/page.hbs
  src/patternfly/layouts/Page/styles.scss
  src/patternfly/sass-utilities/variables.scss
Labels: css

#517 feat(a11y): add scripts for reporting a11y violations
  .gitignore
  README.md
  generateSitemap.js
  package-lock.json
  package.json
  test-a11y/a11yViolationsReporter.js
  test-a11y/index.js
Labels: accessibility

#545 fix(guidelines): improves code guielines for global variables
  src/site/pages/guidelines.md
Labels: Docs

#563 refactor(state modifiers): add modifiers for hover, focus, active, remove modifiers for disabled on form elements except buttons
  src/patternfly/components/AboutModalBox/docs/code.md
  src/patternfly/components/AboutModalBox/styles.scss
  src/patternfly/components/Check/styles.scss
  src/patternfly/components/Dropdown/docs/code.md
  src/patternfly/components/Dropdown/styles.scss
  src/site/pages/guidelines.md
Labels: css

#578 fix(demo-a11y): address demo app related a11y issues, reporter tweaks
  .eslintignore
  src/patternfly/components/AboutModalBox/examples/index.js
  src/patternfly/components/Alert/examples/index.js
  src/patternfly/components/Backdrop/examples/index.js
  src/patternfly/components/BackgroundImage/examples/index.js
  src/patternfly/components/Badge/examples/index.js
  src/patternfly/components/Button/examples/index.js
  src/patternfly/components/Card/examples/index.js
  src/patternfly/components/Check/examples/index.js
  src/patternfly/components/Content/examples/index.js
  src/patternfly/components/Dropdown/examples/index.js
  src/patternfly/components/Form/examples/index.js
  src/patternfly/components/FormControls/examples/index.js
  src/patternfly/components/InputGroup/examples/index.js
  src/patternfly/components/ModalBox/examples/index.js
  src/patternfly/components/Popover/examples/index.js
  src/patternfly/components/Title/examples/index.js
  src/patternfly/components/Tooltip/examples/index.js
  src/site/_site/Documentation/index.js
  src/site/layouts/demo.js
  src/site/layouts/index.js
  test-a11y/a11yViolationsReporter.js
  test-a11y/index.js
Labels: accessibility

#611 A11y Support in CI
  .travis.yml
  package-lock.json
  test-a11y/a11yViolationsReporter.js
  test-a11y/index.js
Labels: accessibility

#639 chore(variables): move global css variables out of patternfly-utilities and into patternfly-base
  package-lock.json
  src/patternfly/_variables.scss
  src/patternfly/patternfly-base.scss
  src/patternfly/sass-utilities/_all.scss
  src/patternfly/sass-utilities/scss-variables.scss
Labels: bug, build

#615 fix(doc): update README
  README.md
Labels: Docs, accessibility

#636 feat(reporting): add PR status indicator for a11y audit
  package-lock.json
  test-a11y/a11yViolationsReporter.js
  test-a11y/config.js
  test-a11y/index.js
  test-a11y/utils.js
Labels: accessibility
