Repository patternfly/patternfly, pull requests merged in 2019-03, with the labels that each got.

#1530 feat(table): add support for caption
  src/patternfly/components/Table/examples/table-simple-example.hbs
  src/patternfly/components/Table/table-caption.hbs
  src/patternfly/components/Table/table.scss
Labels: P1

#1362 feat(AlertDemo): Toasts
  src/patternfly/components/AlertGroup/alert-group.scss
  src/patternfly/demos/Alert/docs/code.md
  src/patternfly/demos/Alert/docs/design.md
  src/patternfly/demos/Alert/examples/alert-toast-example.hbs
  src/patternfly/demos/Alert/examples/index.js
  src/patternfly/demos/Page/examples/page-component-default-nav-header-example.hbs
  src/patternfly/demos/Page/page-demo-default.hbs
  src/patternfly/demos/Page/page-template-header-tools-elements.hbs
Labels: P1

#1496 fix(table): fix bug with content in table cells
  src/patternfly/components/Table/docs/table-simple.md
  src/patternfly/components/Table/examples/table-expandable-example.hbs
  src/patternfly/components/Table/examples/table-simple-with-checkboxes-example.hbs
  src/patternfly/components/Table/examples/table-width-example.hbs
  src/patternfly/components/Table/table-cell-content.hbs
  src/patternfly/components/Table/table-td.hbs
  src/patternfly/components/Table/table-th.hbs
Labels: P1

#1516 fix(inputGroup): background is all white now
  src/patternfly/components/InputGroup/input-group.scss
Labels: P2

#1527 refactor(select): use focusable elements
  src/patternfly/components/ContextSelector/context-selector.scss
  src/patternfly/components/Dropdown/dropdown.scss
  src/patternfly/components/OptionsMenu/options-menu.scss
  src/patternfly/components/Select/docs/select-checkbox.md
  src/patternfly/components/Select/docs/select-multi-typeahead.md
  src/patternfly/components/Select/docs/select-single-typeahead.md
  src/patternfly/components/Select/docs/select-single.md
  src/patternfly/components/Select/examples/select-multi-typeahead-example.hbs
  src/patternfly/components/Select/examples/select-multi-typeahead-expanded-example.hbs
  src/patternfly/components/Select/examples/select-multi-typeahead-expanded-selected-example.hbs
  src/patternfly/components/Select/examples/select-single-expanded-example.hbs
  src/patternfly/components/Select/examples/select-single-expanded-selected-example.hbs
  src/patternfly/components/Select/examples/select-single-typeahead-example.hbs
  src/patternfly/components/Select/examples/select-single-typeahead-expanded-example.hbs
  src/patternfly/components/Select/examples/select-single-typeahead-expanded-selected-example.hbs
  src/patternfly/components/Select/select-checkbox.hbs
  src/patternfly/components/Select/select-single.hbs
  src/patternfly/components/Select/select-toggle-button.hbs
  src/patternfly/components/Select/select-toggle-icon.hbs
  src/patternfly/components/Select/select-toggle-typeahead.hbs
  src/patternfly/components/Select/select-toggle.hbs
  src/patternfly/components/Select/select-typeahead.hbs
  src/patternfly/components/Select/select.hbs
  src/patternfly/components/Select/select.scss
Labels: P3

#1506 fix(datalist): for mobile styling
  src/patternfly/components/DataList/data-list.scss
Labels: P1

#1482 fix(pagination): update content at breakpoints
  src/patternfly/components/Pagination/docs/code.md
  src/patternfly/components/Pagination/examples/pagination-bottom-example.hbs
  src/patternfly/components/Pagination/examples/pagination-top-example.hbs
  src/patternfly/components/Pagination/examples/pagination-top-expanded-example.hbs
  src/patternfly/components/Pagination/pagination-total-items.hbs
  src/patternfly/components/Pagination/pagination.scss
  src/patternfly/components/Toolbar/toolbar.scss
Labels: P1

#1545 fix(table): fix disappearing borders in firefox, workspace styles
  src/patternfly/components/Table/examples/table-compact-example.hbs
  src/patternfly/components/Table/examples/table-simple-example.hbs
  src/patternfly/components/Table/examples/table-simple-with-checkboxes-example.hbs
  src/patternfly/components/Table/examples/table-sortable-example.hbs
  src/patternfly/components/Table/examples/table-width-example.hbs
  src/patternfly/components/Table/table.scss
  src/site/workspace.scss
Labels: P1

#1529 feat(login): add main header description
  src/patternfly/components/Login/docs/code.md
  src/patternfly/components/Login/examples/login-invalid-example.hbs
  src/patternfly/components/Login/examples/login-simple-example.hbs
  src/patternfly/components/Login/login-main-header-desc.hbs
  src/patternfly/components/Login/login.scss
Labels: P1

#1473 fix(switch): remove label from css
  src/patternfly/components/Switch/docs/code.md
  src/patternfly/components/Switch/examples/switch-disabled-example.hbs
  src/patternfly/components/Switch/examples/switch-example.hbs
  src/patternfly/components/Switch/examples/switch-no-label-example.hbs
  src/patternfly/components/Switch/switch-input.hbs
  src/patternfly/components/Switch/switch-label.hbs
  src/patternfly/components/Switch/switch.scss
Labels: on hold

#1548 chore(tabs): remove aria-label from examples
  src/patternfly/components/Tabs/docs/tabs-nav.md
  src/patternfly/components/Tabs/docs/tabs-primary.md
  src/patternfly/components/Tabs/examples/index.js
  src/patternfly/components/Tabs/examples/tabs-filled.hbs
  src/patternfly/components/Tabs/examples/tabs-nav.hbs
  src/patternfly/components/Tabs/examples/tabs-primary.hbs
  src/patternfly/components/Tabs/examples/tabs-scroll.hbs
  src/patternfly/components/Tabs/examples/tabs-secondary.hbs
  src/patternfly/components/Tabs/tabs-list.hbs
  src/patternfly/components/Tabs/tabs.hbs
Labels: p5

#1544 fix(AriaCorrection): fixed several aria violations.
  src/patternfly/components/AboutModalBox/examples/about-modal-box-example.hbs
  src/patternfly/components/Button/examples/button-states-example.hbs
  src/patternfly/upgrade-examples/AlertUpgradeExamples/examples/alert-upgrade-example-pf3-notification.hbs
Labels: P1

#1417 Data Table Demo
  src/patternfly/components/Table/docs/code.md
  src/patternfly/components/Table/table-grid.scss
  src/patternfly/demos/DataTable/data-table-compact-table.hbs
  src/patternfly/demos/DataTable/data-table-compound-expansion-table.hbs
  src/patternfly/demos/DataTable/data-table-expandable-table.hbs
  src/patternfly/demos/DataTable/data-table-main-section-content.hbs
  src/patternfly/demos/DataTable/data-table-main-section-nav.hbs
  src/patternfly/demos/DataTable/data-table-page-header.hbs
  src/patternfly/demos/DataTable/data-table-page-nav.hbs
  src/patternfly/demos/DataTable/data-table-pagination.hbs
  src/patternfly/demos/DataTable/data-table-simple-table.hbs
  src/patternfly/demos/DataTable/data-table-sortable-table.hbs
  src/patternfly/demos/DataTable/data-table-toolbar-no-sort.hbs
  src/patternfly/demos/DataTable/data-table-toolbar.hbs
  src/patternfly/demos/DataTable/docs/code.md
  src/patternfly/demos/DataTable/docs/design.md
  src/patternfly/demos/DataTable/examples/data-table-compact-demo.hbs
  src/patternfly/demos/DataTable/examples/data-table-compound-expansion-demo.hbs
  src/patternfly/demos/DataTable/examples/data-table-expandable-demo.hbs
  src/patternfly/demos/DataTable/examples/data-table-simple-demo.hbs
  src/patternfly/demos/DataTable/examples/data-table-sortable-demo.hbs
  src/patternfly/demos/DataTable/examples/index.js
  test-a11y/config.js
Labels: P3

#1475 fix(emptyState): add sm and lg modifiers for max-width
  src/patternfly/components/EmptyState/docs/code.md
  src/patternfly/components/EmptyState/empty-state.scss
  src/patternfly/components/EmptyState/examples/empty-state-large-example.hbs
  src/patternfly/components/EmptyState/examples/empty-state-small-example.hbs
  src/patternfly/components/EmptyState/examples/index.js
Labels: breaking change, on hold

#1598 refactor(table): change the paddings in the expandable content
  src/patternfly/components/Table/docs/table-expandable.md
  src/patternfly/components/Table/examples/table-compound-expansion-example.hbs
  src/patternfly/components/Table/examples/table-expandable-example.hbs
  src/patternfly/components/Table/table-expandable-row-content.hbs
  src/patternfly/components/Table/table-grid.scss
  src/patternfly/components/Table/table.scss
Labels: breaking change

#1658 refactor(data list): breakpoints should use sm instead of mobile
  src/patternfly/components/DataList/data-list.scss
Labels: breaking change

#1627 chore(toolbar): remove references to pf-c-toolbar__pagination class
  src/patternfly/components/Toolbar/docs/code.md
  src/patternfly/components/Toolbar/examples/toolbar-expanded-example.hbs
  src/patternfly/components/Toolbar/examples/toolbar-pagination-example.hbs
  src/patternfly/demos/DataList/data-list-toolbar.hbs
Labels: breaking change

#1660 fix(dataList): use md breakpoint instead of sm for padding change.
  src/patternfly/components/DataList/data-list.scss
Labels: breaking change

#1628 chore(select): remove unused block
  src/patternfly/components/Select/select.scss
Labels: breaking change

#1626 chore(switch): remove old css label styles
  src/patternfly/components/Switch/switch.scss
Labels: breaking change

#1586 feat(nav): add nav item separator
  src/patternfly/components/Nav/docs/code.md
  src/patternfly/components/Nav/examples/nav-example.hbs
  src/patternfly/components/Nav/examples/nav-expandable-example.hbs
  src/patternfly/components/Nav/examples/nav-simple-list-example.hbs
  src/patternfly/components/Nav/nav-separator.hbs
  src/patternfly/components/Nav/nav.scss
Labels: breaking change

#1629 fix(page): address hidden elements that are visible to screen readers
  src/patternfly/components/Page/page.scss
  src/patternfly/demos/Page/page-template-header-tools-elements.hbs
Labels: breaking change

#1657 refactor(flex-layout): convert device breakpoints to grid breakpoints
  src/patternfly/layouts/Flex/docs/flex-basic.md
  src/patternfly/layouts/Flex/docs/flex-columns.md
  src/patternfly/layouts/Flex/docs/flex-individually-spaced.md
  src/patternfly/layouts/Flex/docs/flex-intro.md
  src/patternfly/layouts/Flex/docs/flex-justification.md
  src/patternfly/layouts/Flex/flex.scss
  src/patternfly/sass-utilities/scss-variables.scss
Labels: breaking change

#1600 refactor(colors): update colors per new brand guidelines
  src/patternfly/_variables.scss
  src/patternfly/components/Alert/alert.scss
  src/patternfly/components/BackgroundImage/background-image.scss
  src/patternfly/components/Badge/badge.scss
  src/patternfly/components/Breadcrumb/breadcrumb.scss
  src/patternfly/components/Button/button.scss
  src/patternfly/components/Chip/chip.scss
  src/patternfly/components/ClipboardCopy/clipboard-copy.scss
  src/patternfly/components/Content/content.scss
  src/patternfly/components/ContextSelector/context-selector.scss
  src/patternfly/components/DataList/data-list.scss
  src/patternfly/components/Dropdown/dropdown.scss
  src/patternfly/components/FormControl/form-control.scss
  src/patternfly/components/InputGroup/input-group.scss
  src/patternfly/components/Login/login.scss
  src/patternfly/components/ModalBox/modal-box.scss
  src/patternfly/components/Nav/nav.scss
  src/patternfly/components/OptionsMenu/options-menu.scss
  src/patternfly/components/Page/page.scss
  src/patternfly/components/Select/select.scss
  src/patternfly/components/Switch/switch.scss
  src/patternfly/components/Table/table-grid.scss
  src/patternfly/components/Table/table.scss
  src/patternfly/components/Tabs/tabs.scss
  src/patternfly/components/Tooltip/tooltip.scss
  src/patternfly/components/Wizard/examples/wizard-example.hbs
  src/patternfly/components/Wizard/examples/wizard-expanded-example.hbs
  src/patternfly/components/Wizard/wizard.scss
  src/patternfly/demos/DataList/examples/data-list-actionable-demo.hbs
  src/patternfly/demos/DataList/examples/data-list-expandable-demo.hbs
  src/patternfly/demos/DataList/examples/data-list-simple-demo.hbs
  src/patternfly/demos/DataList/examples/data-list-simple-without-pagination-demo.hbs
  src/patternfly/demos/DataTable/examples/data-table-compact-demo.hbs
  src/patternfly/demos/DataTable/examples/data-table-compound-expansion-demo.hbs
  src/patternfly/demos/DataTable/examples/data-table-expandable-demo.hbs
  src/patternfly/demos/DataTable/examples/data-table-simple-demo.hbs
  src/patternfly/demos/DataTable/examples/data-table-sortable-demo.hbs
  src/patternfly/demos/Page/examples/page-component-expandable-nav-example.hbs
  src/patternfly/demos/Page/examples/page-component-grouped-nav-example.hbs
  src/patternfly/demos/Page/examples/page-component-horizontal-nav-example.hbs
  src/patternfly/demos/Page/examples/page-component-simple-nav-example.hbs
  src/patternfly/demos/Page/page-demo-default.hbs
  src/patternfly/sass-utilities/colors.scss
  src/patternfly/sass-utilities/placeholders.scss
  src/patternfly/sass-utilities/scss-variables.scss
  src/site/_site/Documentation/styles.scss
  src/site/_site/Navigation/styles.scss
  src/site/_site/Preview/styles.scss
  src/site/workspace.scss
  test-a11y/config.js
  test-a11y/index.js
Labels: breaking change
