Repository patternfly/patternfly, pull requests merged in 2019-08, with the labels that each got.

#2125 chore(build): temporarily disable problematic ci checks
  .travis.yml
Labels: build, infrastructure

#2121 feat(build): move to circleci
  .circleci/config.yml
  .circleci/upload-docs.sh
  .gitignore
  .travis.yml
  build/deploy.sh
  package-lock.json
  package.json
  test-a11y/a11yViolationsReporter.js
  test-a11y/index.js
  test-a11y/utils.js
Labels: infrastructure

#2088 fix(radio): give unique names to fix a11y
  src/patternfly/components/Radio/examples/radio-example.hbs
Labels: accessibility

#2028 feat(select): add a disable modifier
  src/patternfly/components/Select/docs/select-single.md
  src/patternfly/components/Select/examples/index.js
  src/patternfly/components/Select/examples/select-disabled-example.hbs
  src/patternfly/components/Select/select.scss
Labels: update symbol library
