Repository patternfly/patternfly, pull requests merged in 2019-02, with the labels that each got.

#1347 feat(gulpscript): add a stylelint check for undefined css variables
  .cssstylelint
  gulpfile.js
  package-lock.json
  package.json
  src/patternfly/components/AppLauncher/app-launcher.scss
  src/patternfly/components/Login/login.scss
  src/patternfly/components/ModalBox/modal-box.scss
  src/patternfly/components/Table/table.scss
Labels: beta 2

#1339 feat(devx): add commitlint husky pre commit hook
  commitlint.config.js
  package-lock.json
  package.json
Labels: beta 2

#1345 feat(error-handling): add missing error handlers, upgrade a11y pkgs
  .travis.yml
  package-lock.json
  package.json
  test-a11y/config.js
  test-a11y/index.js
Labels: accessibility, enhancement

#1357 Accordion
  src/patternfly/_variables.scss
  src/patternfly/components/Accordion/accordion-expanded-content.hbs
  src/patternfly/components/Accordion/accordion-toggle-icon.hbs
  src/patternfly/components/Accordion/accordion-toggle-text.hbs
  src/patternfly/components/Accordion/accordion-toggle.hbs
  src/patternfly/components/Accordion/accordion.hbs
  src/patternfly/components/Accordion/accordion.scss
  src/patternfly/components/Accordion/docs/code.md
  src/patternfly/components/Accordion/docs/design.md
  src/patternfly/components/Accordion/examples/accordion-fixed-example.hbs
  src/patternfly/components/Accordion/examples/accordion-fluid-example.hbs
  src/patternfly/components/Accordion/examples/index.js
  src/patternfly/sass-utilities/scss-variables.scss
Labels: Feature

#1340 feat(clipboardcopy): add copy to clipboard component
  src/patternfly/_base.scss
  src/patternfly/components/ClipboardCopy/clipboard-copy-expandable-content.hbs
  src/patternfly/components/ClipboardCopy/clipboard-copy-group-copy.hbs
  src/patternfly/components/ClipboardCopy/clipboard-copy-group-toggle.hbs
  src/patternfly/components/ClipboardCopy/clipboard-copy-group.hbs
  src/patternfly/components/ClipboardCopy/clipboard-copy.hbs
  src/patternfly/components/ClipboardCopy/clipboard-copy.scss
  src/patternfly/components/ClipboardCopy/docs/code.md
  src/patternfly/components/ClipboardCopy/examples/clipboard-copy-expansion-example.hbs
  src/patternfly/components/ClipboardCopy/examples/clipboard-copy-no-expansion-example.hbs
  src/patternfly/components/ClipboardCopy/examples/index.js
Labels: Feature

#1467 chore(packaging): dismantle patternfly-base into multiple files
  gulpfile.js
  package.json
  src/patternfly/_base.scss
  src/patternfly/_common.scss
  src/patternfly/_fa-icons.scss
  src/patternfly/_fonts.scss
  src/patternfly/_globals.scss
  src/patternfly/_icons.scss
  src/patternfly/_pf-icons.scss
  src/patternfly/_shield-inheritable.scss
  src/patternfly/_shield-noninheritable.scss
  src/patternfly/components/Switch/docs/design.md
  src/patternfly/patternfly-base.scss
  src/patternfly/patternfly-common.scss
  src/patternfly/patternfly-fa-icons.scss
  src/patternfly/patternfly-fonts.scss
  src/patternfly/patternfly-globals.scss
  src/patternfly/patternfly-icons.scss
  src/patternfly/patternfly-pf-icons.scss
  src/patternfly/patternfly-shield-inheritable.scss
  src/patternfly/patternfly-shield-noninheritable.scss
  src/patternfly/patternfly-themes.scss
  src/patternfly/patternfly-variables.scss
  src/patternfly/sass-utilities/_all.scss
  src/patternfly/sass-utilities/scss-variables.scss
Labels: enhancement

#1510 fix(readme): clean up readme
  README.md
Labels: Docs
