Repository patternfly/patternfly, pull requests merged in 2019-04, with the labels that each got.

#1477 fix(accordion, data-list, page): add padding to child of expandable parent to fix overflow bug.
  src/patternfly/components/Accordion/accordion-expanded-content-body.hbs
  src/patternfly/components/Accordion/accordion-expanded-content.hbs
  src/patternfly/components/Accordion/accordion.scss
  src/patternfly/components/Accordion/docs/code.md
  src/patternfly/components/DataList/data-list-expandable-content-body.hbs
  src/patternfly/components/DataList/data-list-expandable-content.hbs
  src/patternfly/components/DataList/data-list.scss
  src/patternfly/components/DataList/docs/data-list-expandable.md
  src/patternfly/components/DataList/examples/data-list-expandable-example.hbs
  src/patternfly/components/DataList/examples/data-list-width-example.hbs
  src/patternfly/components/Page/docs/code.md
  src/patternfly/components/Page/examples/page-component-nav-vertical-example.hbs
  src/patternfly/components/Page/page-sidebar-body.hbs
  src/patternfly/components/Page/page-sidebar.hbs
  src/patternfly/components/Page/page.scss
  src/patternfly/demos/DataList/data-list-expandable-compact-table.hbs
  src/patternfly/demos/DataList/data-list-expandable-data-list.hbs
  src/patternfly/demos/Page/examples/page-component-expandable-nav-example.hbs
  src/patternfly/demos/Page/examples/page-component-grouped-nav-example.hbs
  src/patternfly/demos/Page/examples/page-component-simple-nav-example.hbs
Labels: breaking change, on hold

#1484 refactor(card): allow for multiple body, add grow modifier
  src/patternfly/components/Card/card.scss
  src/patternfly/components/Card/docs/code.md
  src/patternfly/components/Card/examples/card-multiple-body-example.hbs
  src/patternfly/components/Card/examples/card-no-fill-example.hbs
  src/patternfly/components/Card/examples/index.js
  src/site/workspace.scss
Labels: breaking change, on hold

#1682 refactor(page): do not limit brand img width, use grid in header
  src/patternfly/components/Page/page.scss
Labels: breaking change

#1677 chore(pkg-cleanup): update dev packages, better feedback in a11y audit
  package-lock.json
  package.json
  test-a11y/index.js
Labels: enhancement

#1695 refactor(DataList): kebab always right aligned
  package-lock.json
  src/patternfly/components/DataList/data-list-item-action.hbs
  src/patternfly/components/DataList/data-list-item-content.hbs
  src/patternfly/components/DataList/data-list-item-control.hbs
  src/patternfly/components/DataList/data-list-item-row.hbs
  src/patternfly/components/DataList/data-list-item.hbs
  src/patternfly/components/DataList/data-list.hbs
  src/patternfly/components/DataList/data-list.scss
  src/patternfly/components/DataList/docs/data-list-check-action.md
  src/patternfly/components/DataList/docs/data-list-expandable.md
  src/patternfly/components/DataList/docs/data-list-simple.md
  src/patternfly/components/DataList/examples/data-list-check-action-example.hbs
  src/patternfly/components/DataList/examples/data-list-expandable-example.hbs
  src/patternfly/components/DataList/examples/data-list-simple-example.hbs
  src/patternfly/components/DataList/examples/data-list-width-example.hbs
  src/patternfly/demos/DataList/data-list-actionable-data-list.hbs
  src/patternfly/demos/DataList/data-list-content-1.hbs
  src/patternfly/demos/DataList/data-list-content-2.hbs
  src/patternfly/demos/DataList/data-list-content-4.hbs
  src/patternfly/demos/DataList/data-list-content-5.hbs
  src/patternfly/demos/DataList/data-list-expandable-compact-table.hbs
  src/patternfly/demos/DataList/data-list-expandable-data-list.hbs
  src/patternfly/demos/DataList/data-list-simple-data-list.hbs
  src/patternfly/demos/DataList/data-list-simple-no-pagination-data-list.hbs
Labels: breaking change

#1751 fix(copytoclipboard): add word-wrap to expandable content area
  src/patternfly/components/ClipboardCopy/clipboard-copy.scss
Labels: rc.1

#1747 refactor(flexlayout): update flex layout css to reflect toolbar spacing
  src/patternfly/layouts/Flex/docs/code.md
  src/patternfly/layouts/Flex/docs/design.md
  src/patternfly/layouts/Flex/docs/flex-alignment.md
  src/patternfly/layouts/Flex/docs/flex-basic.md
  src/patternfly/layouts/Flex/docs/flex-columns.md
  src/patternfly/layouts/Flex/docs/flex-individually-spaced.md
  src/patternfly/layouts/Flex/docs/flex-intro.md
  src/patternfly/layouts/Flex/docs/flex-justification.md
  src/patternfly/layouts/Flex/docs/flex-layout-column.md
  src/patternfly/layouts/Flex/docs/flex-layout-responsive.md
  src/patternfly/layouts/Flex/docs/flex-layout.md
  src/patternfly/layouts/Flex/docs/flex-nested.md
  src/patternfly/layouts/Flex/docs/flex-spacing.md
  src/patternfly/layouts/Flex/example-text.hbs
  src/patternfly/layouts/Flex/examples/flex-alignment-example.hbs
  src/patternfly/layouts/Flex/examples/flex-basic-example.hbs
  src/patternfly/layouts/Flex/examples/flex-columns-example.hbs
  src/patternfly/layouts/Flex/examples/flex-individually-spaced-example.hbs
  src/patternfly/layouts/Flex/examples/flex-justification-example.hbs
  src/patternfly/layouts/Flex/examples/flex-layout-column-example.hbs
  src/patternfly/layouts/Flex/examples/flex-layout-example.hbs
  src/patternfly/layouts/Flex/examples/flex-layout-responsive-example.hbs
  src/patternfly/layouts/Flex/examples/flex-nested-example.hbs
  src/patternfly/layouts/Flex/examples/flex-spacing-example.hbs
  src/patternfly/layouts/Flex/examples/index.js
  src/patternfly/layouts/Flex/flex-ba.scss
  src/patternfly/layouts/Flex/flex.scss
  src/patternfly/layouts/Flex/l-flex-item.hbs
  src/patternfly/layouts/Flex/l-flex.hbs
  src/patternfly/utilities/Display/examples/display-grid-example.hbs
  src/patternfly/utilities/Display/examples/index.js
  src/patternfly/utilities/Float/docs/code.md
  src/patternfly/utilities/Float/examples/float-simple-example.hbs
  src/patternfly/utilities/Float/examples/index.js
  src/patternfly/utilities/Float/float.hbs
  src/patternfly/utilities/Float/float.scss
  src/site/workspace.scss
Labels: rc.1
