Repository patternfly/patternfly, pull requests merged in 2019-09, with the labels that each got.

#2214 refactor(flex-layout): wrap flex items, update css
  src/patternfly/layouts/Flex/docs/code.md
  src/patternfly/layouts/Flex/docs/flex-alignment.md
  src/patternfly/layouts/Flex/docs/flex-basic.md
  src/patternfly/layouts/Flex/docs/flex-intro.md
  src/patternfly/layouts/Flex/docs/flex-justification.md
  src/patternfly/layouts/Flex/docs/flex-layout-responsive.md
  src/patternfly/layouts/Flex/docs/flex-layout.md
  src/patternfly/layouts/Flex/docs/flex-spacing.md
  src/patternfly/layouts/Flex/examples/flex-alignment-example.hbs
  src/patternfly/layouts/Flex/examples/flex-basic-example.hbs
  src/patternfly/layouts/Flex/examples/flex-justification-example.hbs
  src/patternfly/layouts/Flex/examples/flex-layout-column-example.hbs
  src/patternfly/layouts/Flex/examples/flex-layout-example.hbs
  src/patternfly/layouts/Flex/examples/flex-layout-responsive-example.hbs
  src/patternfly/layouts/Flex/examples/flex-spacing-example.hbs
  src/patternfly/layouts/Flex/flex.scss
  src/patternfly/layouts/Flex/l-flex-item.hbs
  src/patternfly/sass-utilities/functions.scss
  src/patternfly/sass-utilities/mixins.scss
  src/site/workspace.scss
Labels: Ready to merge

#2005 feat(button): add input modifier
  src/patternfly/components/Button/button.scss
  src/patternfly/components/Button/docs/code.md
  src/patternfly/components/Button/examples/button-states-example.hbs
  src/patternfly/components/Button/examples/button-types-example.hbs
  src/patternfly/components/Button/examples/button-variations-example.hbs
  src/patternfly/components/ClipboardCopy/examples/clipboard-copy-expansion-example.hbs
  src/patternfly/components/ContextSelector/examples/context-selector-example.hbs
  src/patternfly/components/InputGroup/examples/input-group-example.hbs
  src/patternfly/components/InputGroup/input-group.scss
Labels: update symbol library

#2289 Make data list consistent with table
  src/patternfly/components/DataList/data-list.scss
Labels: Ready to merge, update symbol library
