Repository patternfly/patternfly, pull requests merged in 2020-03, with the labels that each got.

#2734 feat(vertical-divider): added vertical divider
  src/patternfly/components/DataToolbar/data-toolbar.scss
  src/patternfly/components/Divider/divider.hbs
  src/patternfly/components/Divider/divider.scss
  src/patternfly/components/Divider/examples/Divider.css
  src/patternfly/components/Divider/examples/Divider.md
  src/patternfly/components/OverflowMenu/overflow-menu.scss
  src/patternfly/layouts/Flex/examples/Flex.css
Labels: released

#2806 Chore(build) - remove IE11 support from build
  .circleci/config.yml
  README.md
  build/gulp/ie11.js
  gulpfile.js
  package.json
Labels: breaking change, infrastructure

#2763 fix(tooltip): reduced space around component
  src/patternfly/components/Tooltip/tooltip.scss
Labels: breaking change

#2762 fix(popover): reduced space between/around elements
  src/patternfly/components/Popover/examples/Popover.md
  src/patternfly/components/Popover/popover-header.hbs
  src/patternfly/components/Popover/popover.scss
Labels: breaking change

#2760 fix(accordion): updated spacing, removed box shadow and shadow variation
  src/patternfly/components/Accordion/accordion.scss
  src/patternfly/components/Accordion/examples/Accordion.md
Labels: breaking change

#2761 fix(modal): reduced spacing
  src/patternfly/components/ModalBox/modal-box.scss
Labels: breaking change

#2757 refactor(tabs): updated to new tab design
  src/patternfly/components/Tabs/__tabs-item.hbs
  src/patternfly/components/Tabs/__tabs-list-secondary.hbs
  src/patternfly/components/Tabs/__tabs-list.hbs
  src/patternfly/components/Tabs/examples/Tabs.css
  src/patternfly/components/Tabs/examples/Tabs.md
  src/patternfly/components/Tabs/tabs-item-icon.hbs
  src/patternfly/components/Tabs/tabs-item-text.hbs
  src/patternfly/components/Tabs/tabs-item.hbs
  src/patternfly/components/Tabs/tabs-scroll-button.hbs
  src/patternfly/components/Tabs/tabs.hbs
  src/patternfly/components/Tabs/tabs.scss
  src/patternfly/demos/MasterDetail/master-detail-panel-tabs.hbs
Labels: breaking change

#2759 fix(card): renamed vars, updated docs
  src/patternfly/components/Card/card.scss
  src/patternfly/components/Card/examples/Card.md
Labels: breaking change
