Repository patternfly/patternfly, pull requests merged in 2020-04, with the labels that each got.

#2912 fix(radio): fixed issue where radio is cut off when comes after label
  src/patternfly/components/Radio/radio.scss
Labels: Release notes reviewed and approved

#2884 style(vertical-nav): refactored css structure
  src/patternfly/_variables.scss
  src/patternfly/components/Nav/examples/Nav.css
  src/patternfly/components/Nav/examples/Nav.md
  src/patternfly/components/Nav/nav-link.hbs
  src/patternfly/components/Nav/nav-toggle-icon.hbs
  src/patternfly/components/Nav/nav.scss
  src/patternfly/components/Page/page.scss
  src/patternfly/demos/Page/examples/Page.md
  src/patternfly/demos/Page/page-demo-default.hbs
  src/patternfly/demos/Page/page-demo-expandable-nav.hbs
  src/patternfly/sass-utilities/scss-variables.scss
Labels: breaking change

#2952 fix(bug): updated steps to be used for dev env
  README.md
Labels: infrastructure

#2957 Readme fix 2947
  README.md
Labels: infrastructure

#2960 Moving some top level scss files into directory structure"
  .circleci/config.yml
  build/gulp/copy.js
  gulpfile.js
  src/patternfly/_icons.scss
  src/patternfly/_pf-icons.scss
  src/patternfly/base/_base.scss
  src/patternfly/base/_chart-globals.scss
  src/patternfly/base/_common.scss
  src/patternfly/base/_fa-icons.scss
  src/patternfly/base/_fonts.scss
  src/patternfly/base/_globals.scss
  src/patternfly/base/_icons.scss
  src/patternfly/base/_pf-icons.scss
  src/patternfly/base/_shield-inheritable.scss
  src/patternfly/base/_shield-noninheritable.scss
  src/patternfly/base/_themes.scss
  src/patternfly/base/_variables.scss
  src/patternfly/base/patternfly-common.scss
  src/patternfly/base/patternfly-fa-icons.scss
  src/patternfly/base/patternfly-fonts.scss
  src/patternfly/base/patternfly-globals.scss
  src/patternfly/base/patternfly-icons.scss
  src/patternfly/base/patternfly-pf-icons.scss
  src/patternfly/base/patternfly-shield-inheritable.scss
  src/patternfly/base/patternfly-shield-noninheritable.scss
  src/patternfly/base/patternfly-themes.scss
  src/patternfly/base/patternfly-variables.scss
  src/patternfly/patternfly-addons.scss
  src/patternfly/patternfly-base.scss
  src/patternfly/patternfly-charts.scss
  src/patternfly/patternfly-common.scss
  src/patternfly/patternfly-fa-icons.scss
  src/patternfly/patternfly-fonts.scss
  src/patternfly/patternfly-globals.scss
  src/patternfly/patternfly-icons.scss
  src/patternfly/patternfly-imports.scss
  src/patternfly/patternfly-pf-icons.scss
  src/patternfly/patternfly-shield-inheritable.scss
  src/patternfly/patternfly-shield-noninheritable.scss
  src/patternfly/patternfly-themes.scss
  src/patternfly/patternfly-variables.scss
  src/patternfly/patternfly.scss
Labels: infrastructure

#2766 fix(form): refactored label/control sections, added label help
  src/patternfly/components/Form/examples/Form.md
  src/patternfly/components/Form/form-group-control.hbs
  src/patternfly/components/Form/form-group-label-help.hbs
  src/patternfly/components/Form/form-group-label.hbs
  src/patternfly/components/Form/form-label-required.hbs
  src/patternfly/components/Form/form-label-text.hbs
  src/patternfly/components/Form/form-label.hbs
  src/patternfly/components/Form/form.scss
  src/patternfly/demos/BasicForms/examples/BasicForms.md
Labels: breaking change
